[tool.poetry]
name = "robotframework-jmslibrary"
version = "0.3.0.dev0"
description = ""
authors = ["Many Kasiriha <many.kasiriha@dbschenker.com>",
"Andre Krautschick <andre.krautschick@eurocontrol.int"]
readme = "README.md"
packages = [{include = "JMS"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
jpype1 = "^1.4.1"
robotframework = "*"
robotframework-assertion-engine = "^1.1.1"


#[tool.poetry.group.dev.dependencies]
#black = "^23.7.0"
#invoke = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
